// Placeholder. The real contents of this directory are generated by
//
//   pnpm --filter @pwrsnap/codex-app-server-protocol generate
//
// which invokes `codex app-server generate-ts --out ./src` against the
// locally-installed Codex CLI. The generator produces one .ts file per
// Rust type in the Codex protocol crate, plus a barrel `index.ts` (this
// file) and a `v2/` subdirectory with the v2 surface.
//
// Run the generator before you start working on AI pipelines (Phase 4+).
// Commit the diff so the rest of the workspace builds without a Codex
// install at hand.

export {};
