const DOCUMENT_ID = /^[A-Za-z0-9_-]{16,128}$/;

const liveDocumentByWebContents = new Map<number, string>();
const navigatingWebContents = new Set<number>();

export function isHotkeyRecorderDocumentId(value: unknown): value is string {
  return typeof value === "string" && DOCUMENT_ID.test(value);
}

/**
 * Admit the opaque epoch generated by one preload document. The transport
 * calls this only after proving the IPC sender is the webContents' current
 * main frame; an old document cannot re-introduce its epoch after navigation.
 */
export function admitHotkeyRecorderDocument(
  webContentsId: number,
  documentId: unknown
): string | null {
  if (
    !Number.isSafeInteger(webContentsId) ||
    webContentsId < 0 ||
    navigatingWebContents.has(webContentsId) ||
    !isHotkeyRecorderDocumentId(documentId)
  ) {
    return null;
  }
  liveDocumentByWebContents.set(webContentsId, documentId);
  return documentId;
}

/** Fence the current epoch synchronously before asynchronous lease cleanup. */
export function fenceHotkeyRecorderDocument(
  webContentsId: number
): string | null {
  navigatingWebContents.add(webContentsId);
  const documentId = liveDocumentByWebContents.get(webContentsId) ?? null;
  liveDocumentByWebContents.delete(webContentsId);
  return documentId;
}

/** A completed load may introduce a new preload-owned document epoch. */
export function allowNextHotkeyRecorderDocument(webContentsId: number): void {
  navigatingWebContents.delete(webContentsId);
  liveDocumentByWebContents.delete(webContentsId);
}

/** True only for the epoch currently admitted on this live webContents. */
export function isLiveHotkeyRecorderDocument(
  webContentsId: number,
  documentId: string
): boolean {
  return (
    !navigatingWebContents.has(webContentsId) &&
    liveDocumentByWebContents.get(webContentsId) === documentId
  );
}
