// macOS menubar tray + anchored popover. Phase 1.7 refinements per
// the deepening review:
//   • Real 16×16/@2x template PNG (generated by scripts/generate-tray-icon.mjs
//     from the brand mark SVG). Template images automatically adapt
//     to dark / light / accent menubars — setTitle() text doesn't.
//   • Popover dismiss-on-blur with a 120ms debounce + DevTools open
//     guard + cursor-bounds check, matching Raycast / Linear / Bartender
//     patterns. Avoids the false-positives the original blur-only
//     handler caused (DevTools focus, dragging the popover, focus
//     hopping to a child popover all looked like "click outside").
//   • screen.getDisplayMatching(trayBounds) for multi-display anchoring.
//   • Right-click opens a real Menu (Quit / Open / Settings) — popover
//     is for the rich UI, the native menu is the fallback.

import { existsSync } from "node:fs";
import { join } from "node:path";
import {
  app,
  ipcMain,
  Menu,
  type MenuItemConstructorOptions,
  nativeImage,
  screen,
  Tray,
  type BrowserWindow
} from "electron";
import {
  DEFAULT_HOTKEYS,
  type RecordingState,
  type Settings
} from "@pwrsnap/shared";
import { bus } from "./command-bus";
import { getMainLogger } from "./log";
import { getRuntimeProcessRole } from "./process-role";
import {
  isRecordingActive,
  subscribeToRecordingState
} from "./recording/recording-state";
import { createTrayWindow, positionTrayWindow } from "./window";

const log = getMainLogger("pwrsnap:tray");

const BLUR_DISMISS_DEBOUNCE_MS = 120;

/**
 * Extra menu items appended to the right-click menu (after a
 * separator). Used by the dev seeder to add "Seed perf dataset > …"
 * entries in DEV builds. Empty in production. Not a registration API
 * with deduplication — caller controls the array.
 */
let extraMenuItems: MenuItemConstructorOptions[] = [];

/**
 * Append items to the tray's right-click menu. Returns a `restore`
 * function that drops the items. Call from `registerDevSeeder()`.
 */
export function setExtraTrayMenuItems(items: MenuItemConstructorOptions[]): () => void {
  extraMenuItems = items;
  return () => {
    extraMenuItems = [];
  };
}
const TRAY_RESIZE_CHANNEL = "tray:resize";

/** Hard floor + ceiling so a renderer bug can't shrink to nothing or grow off-screen.
 *  Ceiling raised from 720 → 880 (original redesign) → 1040 (when the
 *  last-snap video export row swapped the 2-button GIF/MP4 strip for
 *  the full 6-card grid (GIF L/M/H + MP4 L/M/H) — same chrome the
 *  library DetailRail renders, so the user can copy / drag any preset
 *  straight from the tray). The 6-card grid adds ~120px over the
 *  prior 2-button row. Image tray stays well under the old 880
 *  ceiling; the bump is purely for video. The popover is anchored
 *  top-down from the menubar tray icon, so growing taller doesn't
 *  push off-screen — Electron clamps to workArea automatically. */
const TRAY_HEIGHT_MIN = 200;
const TRAY_HEIGHT_MAX = 1040;
/** Window width is fixed by the design — must match `.ps-tray { width }`
    in library.css. Bumped from 380 → 440 because the 2-column mode
    grid (Region/Window, Full/All, Timed) was clipping the right column
    at 380, especially with multi-key shortcuts like ⌘⇧F that need 56px
    just for the kbds. */
const TRAY_WIDTH = 440;

let tray: Tray | null = null;
let trayWindow: BrowserWindow | null = null;
let pendingDismiss: ReturnType<typeof setTimeout> | null = null;
let currentTrayHotkeys: Settings["hotkeys"] = { ...DEFAULT_HOTKEYS };

function idleTrayTooltip(): string {
  return "PwrSnap — Quick Capture";
}

export function setTrayHotkeys(hotkeys: Settings["hotkeys"]): void {
  currentTrayHotkeys = { ...hotkeys };
  if (tray !== null && !isRecordingActive()) {
    tray.setToolTip(idleTrayTooltip());
  }
}

/**
 * Synchronously hide the tray popover, bypassing the 120ms blur-dismiss
 * debounce. Called from the capture flow right before we shell out to
 * `screencapture` so the popover doesn't show up in the captured frame.
 *
 * The tray popover is a `BrowserWindow` (not an `NSStatusItem` menu),
 * so it does NOT auto-dismiss on click the way a real status-bar menu
 * does — we have to dismiss it ourselves. Belt-and-suspenders against
 * a future change to a real `NSStatusItem`-backed menu (which would
 * dismiss synchronously, and then this becomes a defensible no-op).
 *
 * Idempotent and null-safe — calling on a destroyed or already-hidden
 * window is a no-op. Cancels any pending blur-debounce timeout so we
 * don't get a double-hide jitter when the queued timer fires later.
 */
export function hideTrayPopoverIfVisible(): void {
  if (pendingDismiss !== null) {
    clearTimeout(pendingDismiss);
    pendingDismiss = null;
  }
  if (trayWindow !== null && !trayWindow.isDestroyed() && trayWindow.isVisible()) {
    trayWindow.hide();
  }
}

function resolveTrayIconPath(): string {
  // macOS uses an alpha-only *template* PNG (the system tints it for
  // dark/light/accent menubars). Windows/Linux have no template tinting, so
  // they ship the colored brand icon (tangerine) instead.
  const fileName =
    process.platform === "darwin" ? "tray-icon-template.png" : "tray-icon.png";
  // Production: shipped under Contents/Resources/ via electron-builder.yml's
  // `extraResources`. nativeImage auto-loads the @2x/@3x siblings when
  // given the base path, as long as they're in the same directory.
  const productionPath = join(process.resourcesPath, fileName);
  if (existsSync(productionPath)) return productionPath;
  // Dev: served straight out of the workspace `build/` dir.
  return join(app.getAppPath(), "build", fileName);
}

function ensureTrayWindow(): BrowserWindow {
  if (trayWindow !== null && !trayWindow.isDestroyed()) return trayWindow;
  const window = createTrayWindow();
  trayWindow = window;
  wireBlurDismiss(window);
  // NOTE: there is deliberately no `zoom-changed` hook here. That
  // event is mouse-wheel-only — it does NOT fire for setZoomFactor,
  // the View-menu zoomIn/zoomOut roles, or Chromium HostZoomMap
  // same-origin propagation (verified empirically), so main cannot
  // observe the zoom changes that actually happen in production.
  // Instead the renderer detects effective-zoom changes itself via a
  // devicePixelRatio media-query listener (see TrayMenu.tsx) and
  // re-posts through the resize channel; wireTrayResizeChannel then
  // re-converts CSS px → DIP with the current zoomFactor. See
  // docs/solutions/2026-07-15-popover-zoom-remeasure-dpr.md.
  window.on("closed", () => {
    if (trayWindow === window) trayWindow = null;
  });
  return window;
}

/**
 * Listen for tray-renderer resize requests and `setContentSize` so the
 * popover hugs its content. Each call also re-positions to keep the
 * top-right corner anchored under the tray icon (otherwise growing
 * down would push the popover off-screen on a tall display).
 *
 * Idempotent — safe to call from both the production `installTray`
 * boot path and the E2E `showTrayPopoverForE2E` test helper without
 * stacking duplicate ipcMain listeners.
 */
let trayResizeChannelWired = false;
function wireTrayResizeChannel(): void {
  if (trayResizeChannelWired) return;
  trayResizeChannelWired = true;
  ipcMain.on(TRAY_RESIZE_CHANNEL, (_event, payload: unknown) => {
    if (
      payload === null ||
      typeof payload !== "object" ||
      typeof (payload as { height: unknown }).height !== "number"
    ) {
      return;
    }
    const requestedCss = (payload as { height: number }).height;
    if (!Number.isFinite(requestedCss)) return;
    if (trayWindow === null || trayWindow.isDestroyed()) return;
    // Renderer measures in CSS pixels (post-zoom). `setContentSize`
    // takes DIP (zoom-independent). When the session's zoomFactor is
    // not 1.0 (e.g. user Cmd-+'d in the library — zoom is shared
    // per-origin via Chromium's HostZoomMap), the two units diverge:
    // a 600 CSS px tall popover at 1.32× zoom is 600 × 1.32 ≈ 792
    // DIP. Without this conversion, the BrowserWindow ends up
    // shorter than the rendered content needs and the popover
    // visibly clips.
    const zoom = trayWindow.webContents.zoomFactor;
    const requestedDip = Math.ceil(requestedCss * zoom);
    const clamped = Math.max(TRAY_HEIGHT_MIN, Math.min(TRAY_HEIGHT_MAX, requestedDip));
    if (trayWindow.getContentSize()[1] === clamped) return;
    // Belt-and-braces: every resize call lifts the implicit minimum
    // size first. The createTrayWindow call already does this once on
    // first construction, but if anything later re-asserts a min size
    // (an unrelated Electron API call, a future BrowserWindow.setBounds
    // wrapper, etc.) the resize would silently clamp again. Cheap to
    // re-call — Electron coalesces same-value setMinimumSize calls.
    trayWindow.setMinimumSize(0, 0);
    trayWindow.setContentSize(TRAY_WIDTH, clamped, false);
    if (tray !== null && trayWindow.isVisible()) {
      positionTrayWindow(trayWindow, tray.getBounds());
    }
  });
}

/**
 * Dismiss-on-blur with two false-positive guards:
 *   - DevTools opened on the tray (developer is debugging)
 *   - Re-focused during the debounce (false-positive blur from a
 *     macOS focus hop)
 *
 * The cursor-inside-bounds check that used to live here was
 * dropping legitimate dismissals — right-clicking the dock icon
 * fires blur but the cursor often grazes the tray window during
 * the debounce, which the old check interpreted as "user is still
 * here." For a transient popover we want to err on dismissing.
 */
function wireBlurDismiss(window: BrowserWindow): void {
  window.on("blur", () => {
    if (pendingDismiss !== null) return;
    pendingDismiss = setTimeout(() => {
      pendingDismiss = null;
      if (trayWindow === null || trayWindow.isDestroyed()) return;
      // DevTools open on the tray = developer using it; never auto-dismiss.
      if (trayWindow.webContents.isDevToolsOpened()) return;
      // If the window regained focus during the debounce window, abort.
      if (trayWindow.isFocused()) return;
      trayWindow.hide();
    }, BLUR_DISMISS_DEBOUNCE_MS);
  });
  window.on("focus", () => {
    if (pendingDismiss !== null) {
      clearTimeout(pendingDismiss);
      pendingDismiss = null;
    }
  });
}

export function installTray(): Tray {
  if (tray !== null) return tray;

  wireTrayResizeChannel();

  const iconPath = resolveTrayIconPath();
  const icon = nativeImage.createFromPath(iconPath);
  if (icon.isEmpty()) {
    log.warn("tray icon image is empty — falling back to setTitle text", { iconPath });
  }
  // Template image is a macOS concept (alpha-only, system-tinted). On
  // Windows/Linux the icon carries its own color — marking it as a template
  // would blank it out.
  if (process.platform === "darwin") {
    icon.setTemplateImage(true);
  }

  tray = new Tray(icon);
  tray.setToolTip(idleTrayTooltip());
  // Split mode only: double-click opens the Library (a real action), so
  // don't suppress double-clicks. Combined mode keeps the prior behavior
  // (ignore double-clicks) so the experiment-off app is unchanged — the
  // double-click handler below is wired only outside combined.
  const trayDoubleClickOpensLibrary = getRuntimeProcessRole() !== "combined";
  tray.setIgnoreDoubleClickEvents(!trayDoubleClickOpensLibrary);

  // Recording state → tray indicator. While recording, prepend "● " to
  // the tooltip + tray title so the menubar telegraphs the live state
  // at a glance (matches OBS / CleanShot conventions). The right-
  // click menu also flips its top items (read in the `right-click`
  // handler below from `isRecordingActive()`).
  subscribeToRecordingState((state) => {
    if (tray === null) return;
    applyRecordingStateToTray(tray, state);
  });

  tray.on("click", () => toggleTrayWindow());
  if (trayDoubleClickOpensLibrary) {
    tray.on("double-click", () => {
      // The first click of the pair already fired `click` and toggled
      // the popover — drop it so the Library doesn't open underneath an
      // orphaned popover.
      if (trayWindow !== null && !trayWindow.isDestroyed() && trayWindow.isVisible()) {
        trayWindow.hide();
      }
      // library:focus spawns (or raises) the Library — same verb as the
      // context menu's "Open Library".
      void bus.dispatch("library:focus", {}, { principal: "ipc" });
    });
  }
  tray.on("right-click", () => {
    const trayBounds = tray?.getBounds();
    // Always dismiss the popover before the context menu appears —
    // having both visible at once is confusing UX (and was the
    // dock-icon-right-click reproduction the user reported).
    if (trayWindow !== null && !trayWindow.isDestroyed() && trayWindow.isVisible()) {
      trayWindow.hide();
    }
    const menu = Menu.buildFromTemplate(buildTrayContextMenuTemplate(trayBounds));
    tray?.popUpContextMenu(menu);
  });

  // Pre-warm the popover BrowserWindow at boot. Without this, the
  // first tray click pays the full cost of spawning a Chromium
  // renderer process, loading the renderer bundle, parsing it, and
  // waiting for the initial measurement to settle before the
  // BrowserWindow snaps from its constructor frame (440×440) to the
  // measured content height. With pre-warm, the window is already
  // sized + measured (off-screen, hidden) by the time the user
  // clicks — `toggleTrayWindow` just calls `showInactive()` + `focus()`.
  //
  // Cost: the tray BrowserWindow stays resident from boot. Under
  // Chromium's process-per-site default the tray, library, and
  // region selectors all load the same file:// origin and share one
  // renderer process — so the marginal memory cost is the tray
  // window's display surface, not a separate renderer process. The
  // tray is the most-clicked surface in the menubar UX; this trade
  // pays back on the first click and every click after.
  //
  // We deliberately don't `show()` here — the window stays
  // off-screen + hidden. The renderer's `useLayoutEffect` posts the
  // initial resize over the IPC channel exactly as it does on a real
  // click; `wireTrayResizeChannel` sizes the (hidden) window to match.
  prewarmTrayWindow();

  log.info("tray installed", { iconPath });
  return tray;
}

/**
 * Off-screen pre-warm of the tray BrowserWindow. Idempotent — safe
 * to call from `installTray()` AND from the E2E bridge before
 * `measureTrayFirstPaintForE2E`. The window is created in its hidden
 * state via `createTrayWindow`, attached to the resize channel, and
 * left alone: Chromium spawns the renderer, loads the bundle, runs
 * the initial React render + `useLayoutEffect` measurement, and the
 * `tray:resize` IPC sizes the (hidden) window to its content height
 * — all before the user's first click. The first user-visible paint
 * happens at `showInactive()` time on click, but it lands at the
 * already-correct size, so no resize flicker is visible.
 *
 * Returns the window so E2E callers can attach test-only listeners
 * before the renderer mounts; production callers (just `installTray`)
 * discard the return value.
 */
export function prewarmTrayWindow(): BrowserWindow {
  wireTrayResizeChannel();
  return ensureTrayWindow();
}

function toggleTrayWindow(): void {
  const window = ensureTrayWindow();
  if (window.isVisible()) {
    window.hide();
    return;
  }
  const bounds = tray!.getBounds();
  positionTrayWindow(window, bounds);
  // Apply vibrancy *after* position so external displays don't render
  // it opaque — known Electron quirk on Sonoma+ multi-monitor setups.
  try {
    window.setVibrancy("popover");
  } catch {
    /* not all macOS versions accept all vibrancy values; non-fatal */
  }
  // Show, then promote to key window. The two-step matters:
  //
  //   1. `showInactive()` paints the panel without activating the
  //      owning app (this is what `type: 'panel'` is for — a
  //      non-activating NSPanel).
  //   2. `focus()` makes the panel the macOS *key window*. On
  //      Electron 28+ with PR #40307 this is non-activating for
  //      panel windows — the panel becomes key, but the app does
  //      NOT come to the foreground.
  //
  // Why bother making it key? Click-outside-to-dismiss. Cocoa fires
  // `NSWindowDidResignKeyNotification` (which Electron surfaces as
  // `blur`) only when the panel was previously key. Without step 2
  // the popover never becomes key, so blur never fires, so the
  // dismiss-on-blur handler in wireBlurDismiss can't see clicks
  // outside the popover. Promoting to key on show reverses that —
  // any click outside the popover (other apps, the desktop, another
  // PwrSnap window) costs the panel its key status and fires blur.
  //
  // The Library-cascade concern from the original implementation
  // (Cocoa picking the next-key window of our app when the panel
  // hides) is handled by the floating-level focus-sink installed
  // at startup — see focus-sink.ts.
  window.showInactive();
  window.focus();
}

export function disposeTray(): void {
  if (pendingDismiss !== null) {
    clearTimeout(pendingDismiss);
    pendingDismiss = null;
  }
  ipcMain.removeAllListeners(TRAY_RESIZE_CHANNEL);
  trayResizeChannelWired = false;
  if (trayWindow !== null && !trayWindow.isDestroyed()) {
    trayWindow.destroy();
    trayWindow = null;
  }
  if (tray !== null) {
    tray.destroy();
    tray = null;
  }
  currentTrayHotkeys = { ...DEFAULT_HOTKEYS };
}

/**
 * E2E-only: ensure the tray popover BrowserWindow exists, the resize
 * channel is wired, and the window is visible. Skips the `Tray` icon
 * creation that `installTray()` does — tests don't need a menubar
 * NSStatusItem, and creating one in headless CI environments is
 * unreliable.
 *
 * Positions the popover at a fixed top-left location on the primary
 * display so spec assertions about bounds are stable across machines.
 */
export function showTrayPopoverForE2E(): void {
  wireTrayResizeChannel();
  const window = ensureTrayWindow();
  // Stable test position: top-left of the primary display, indented
  // a few pixels off the menubar. Production positioning happens via
  // positionTrayWindow + the tray icon's bounds; tests don't have a
  // tray icon, so we just pin the window somewhere predictable.
  const primary = screen.getPrimaryDisplay();
  const wa = primary.workArea;
  window.setPosition(wa.x + 8, wa.y + 8, false);
  window.showInactive();
  window.focus();
}

/** E2E-only: hide the tray popover synchronously (no debounce). */
export function hideTrayPopoverForE2E(): void {
  hideTrayPopoverIfVisible();
}

/**
 * E2E-only: measurement of "tray click → fully-painted popover" for
 * the perf baseline / regression spec. Two operating modes,
 * determined by the live tray-window state:
 *
 *   - cold: no tray window exists. The bridge creates it, attaches
 *     event listeners, shows it, waits for the renderer's resize to
 *     stabilize. Mirrors today's first-click production flow.
 *   - prewarmed: a tray window already exists, created at boot by
 *     `prewarmTrayWindow()`. The bridge skips construction and just
 *     times `show() → paint`. Mirrors the optimized production flow.
 *
 * Checkpoint set is the same shape across both modes — fields that
 * don't apply in `prewarmed` (windowCreated, domReady, etc.) come
 * back as `null` so spec consumers can print one uniform table.
 */
export async function measureTrayFirstPaintForE2E(options: {
  stableMs?: number;
  timeoutMs?: number;
  /**
   * Minimum content height (DIP) the popover must reach before its size
   * is accepted as "stable". Defaults to 0 (no gate).
   *
   * The "no resize for stableMs" heuristic alone is unsound when the
   * popover's final height depends on an async reflow that lands AFTER a
   * quiet period: a seeded last-snap preview is fetched over IPC and its
   * image decoded via pwrsnap-capture://, so the renderer first measures
   * the empty/text-only height (~248) and only later re-measures to the
   * full seeded height (~634). When that second reflow arrives more than
   * stableMs after the first measurement — routine on the slower VS2026
   * runner image — the bare heuristic breaks at ~248, the empty-tray
   * band. Callers that know they seeded content pass the expected floor
   * so the measurement waits for the real content instead of sampling
   * the transient empty state. A height that never reaches the floor
   * times out (`timedOut: true`) — a genuine regression still fails.
   */
  minStableHeight?: number;
} = {}): Promise<{
  mode: "cold" | "prewarmed";
  windowCreated: number | null;
  domReady: number | null;
  didFinishLoad: number | null;
  readyToShow: number | null;
  isVisible: number | null;
  firstResize: number | null;
  stableResize: number | null;
  finalContentHeight: number | null;
  resizeCount: number;
  timedOut: boolean;
}> {
  const stableMs = options.stableMs ?? 300;
  const timeoutMs = options.timeoutMs ?? 10_000;
  const minStableHeight = options.minStableHeight ?? 0;

  const alreadyExists = trayWindow !== null && !trayWindow.isDestroyed();
  const mode: "cold" | "prewarmed" = alreadyExists ? "prewarmed" : "cold";

  if (alreadyExists && trayWindow!.isVisible()) {
    throw new Error("measureTrayFirstPaintForE2E: tray window already visible; hide first");
  }

  const t0 = performance.now();
  const mark = (): number => Math.round((performance.now() - t0) * 100) / 100;

  // Probe listener for the renderer's resize channel. Observes the
  // production listener (wireTrayResizeChannel) without interfering.
  // In the prewarmed case the renderer has already posted its initial
  // measurement during pre-warm; no new resize is expected unless the
  // content changes between pre-warm and show.
  let firstResize: number | null = null;
  let lastResizeAt = 0;
  let resizeCount = 0;
  const probe = (_event: Electron.IpcMainEvent, payload: unknown): void => {
    if (
      payload === null ||
      typeof payload !== "object" ||
      typeof (payload as { height: unknown }).height !== "number" ||
      !Number.isFinite((payload as { height: number }).height)
    ) {
      return;
    }
    resizeCount += 1;
    if (firstResize === null) firstResize = mark();
    lastResizeAt = performance.now();
  };
  // Belt-and-suspenders: wire the production channel in case the
  // bridge runs before installTray() / prewarmTrayWindow() did
  // (E2E mode skips installTray). Idempotent.
  wireTrayResizeChannel();
  ipcMain.on(TRAY_RESIZE_CHANNEL, probe);

  let windowCreated: number | null = null;
  let domReady: number | null = null;
  let didFinishLoad: number | null = null;
  let readyToShow: number | null = null;

  const window = ensureTrayWindow();
  if (!alreadyExists) {
    windowCreated = mark();
    // `ensureTrayWindow` calls `createTrayWindow` which calls
    // `loadRenderer` synchronously — for a same-tick file:// load,
    // `dom-ready` / `did-finish-load` could fire before we attach
    // listeners on the next microtask. Check the load state first
    // and mark immediately if we already missed the event; otherwise
    // attach the `once` listener as usual.
    if (window.webContents.isLoadingMainFrame()) {
      window.webContents.once("dom-ready", () => {
        domReady = mark();
      });
      window.webContents.once("did-finish-load", () => {
        didFinishLoad = mark();
      });
    } else {
      // Already past load — both events fired during construction.
      // Best-effort: mark them at the same instant so spec consumers
      // see a consistent "first paint landed sub-listener-attach" value.
      domReady = mark();
      didFinishLoad = mark();
    }
    window.once("ready-to-show", () => {
      readyToShow = mark();
    });
  }

  // Mirror showTrayPopoverForE2E's positioning so apples-to-apples
  // with tray-sizing.spec.ts.
  const primary = screen.getPrimaryDisplay();
  const wa = primary.workArea;
  window.setPosition(wa.x + 8, wa.y + 8, false);
  window.showInactive();
  window.focus();

  let isVisible: number | null = null;
  const deadline = performance.now() + timeoutMs;
  const startedAt = performance.now();
  // In the prewarmed case there's no fresh resize to wait on — the
  // renderer measured during pre-warm and the window is already at
  // its content height. Hold long enough for the OS to swap the off-
  // screen window in and the spec can read back isVisible.
  const minimumPrewarmedHoldMs = 60;
  // The seeded content (if any) must have actually landed before we
  // accept the size as final — see `minStableHeight`. Cheap: a
  // synchronous getContentSize read, no IPC. Trivially true for the
  // empty-tray scenarios (their floor is below the empty height) and
  // for callers that pass no floor.
  const heightSettled = (): boolean =>
    !window.isDestroyed() && window.getContentSize()[1] >= minStableHeight;
  let timedOut = true;
  while (performance.now() < deadline) {
    if (isVisible === null && !window.isDestroyed() && window.isVisible()) {
      isVisible = mark();
    }
    if (mode === "prewarmed") {
      if (
        isVisible !== null &&
        performance.now() - startedAt >= minimumPrewarmedHoldMs &&
        heightSettled()
      ) {
        timedOut = false;
        break;
      }
    } else if (
      lastResizeAt > 0 &&
      performance.now() - lastResizeAt >= stableMs &&
      heightSettled()
    ) {
      timedOut = false;
      break;
    }
    await new Promise((resolve) => setTimeout(resolve, 10));
  }

  ipcMain.off(TRAY_RESIZE_CHANNEL, probe);

  const stableResize = lastResizeAt > 0 ? Math.round((lastResizeAt - t0) * 100) / 100 : null;
  const finalContentHeight = !window.isDestroyed() ? window.getContentSize()[1] : null;

  return {
    mode,
    windowCreated,
    domReady,
    didFinishLoad,
    readyToShow,
    isVisible,
    firstResize,
    stableResize,
    finalContentHeight,
    resizeCount,
    timedOut
  };
}

/**
 * Show a single character/number next to the menubar tray icon — used
 * by the Timed (5s) capture flow to render the countdown without
 * popping any window that would steal focus from a menu the user is
 * staging for the shot. `null` clears the title back to icon-only.
 *
 * No-op when the Tray isn't installed (E2E specs that exercise the
 * popover without a real NSStatusItem).
 */
export function setTrayCountdown(text: string | null): void {
  if (tray === null) return;
  tray.setTitle(text ?? "");
}

export function buildTrayContextMenuTemplate(
  trayBounds?: Electron.Rectangle
): MenuItemConstructorOptions[] {
  // Top of menu changes while recording — the user almost certainly
  // came here to stop, so make Stop the first item and demote the
  // Capture row. Cancel sits next to Stop so a botched recording
  // can be aborted without persisting a Library row.
  const recordingItems: MenuItemConstructorOptions[] = isRecordingActive()
    ? [
        {
          label: "● Recording — Stop",
          click: () => {
            void bus.dispatch("recording:stop", {}, { principal: "ipc" });
          }
        },
        {
          label: "Cancel Recording",
          click: () => {
            void bus.dispatch("recording:cancel", {}, { principal: "ipc" });
          }
        },
        { type: "separator" }
      ]
    : [];
  const baseTemplate: MenuItemConstructorOptions[] = [
    {
      label: "Quick Capture…",
      ...(currentTrayHotkeys.quickCapture !== ""
        ? { accelerator: currentTrayHotkeys.quickCapture }
        : {}),
      click: () => {
        void bus.dispatch("capture:interactive", { mode: "auto" }, { principal: "ipc" });
      }
    },
    {
      // The app's two headline verbs sit together above the rule —
      // snap (Quick Capture) then record (Record Video) — mirroring the
      // tray popover + Library header. No sourceWindowId on a tray
      // dispatch, so the record leaves the Library as a valid target.
      label: "Record Video…",
      ...(currentTrayHotkeys.videoCapture !== ""
        ? { accelerator: currentTrayHotkeys.videoCapture }
        : {}),
      click: () => {
        void bus.dispatch("capture:videoInteractive", {}, { principal: "ipc" });
      }
    },
    { type: "separator" },
    {
      label: "Open Library",
      click: () => {
        void bus.dispatch("library:focus", {}, { principal: "ipc" });
      }
    },
    {
      label: "Settings…",
      click: () => {
        const options: Parameters<typeof bus.dispatch>[2] = { principal: "ipc" };
        if (trayBounds !== undefined) {
          options.sourceBounds = trayBounds;
        }
        void bus.dispatch("settings:open", {}, options);
      }
    }
  ];
  const extras = extraMenuItems.length > 0
    ? [{ type: "separator" } as MenuItemConstructorOptions, ...extraMenuItems]
    : [];
  return [
    ...recordingItems,
    ...baseTemplate,
    ...extras,
    { type: "separator" },
    {
      label: "Quit PwrSnap",
      click: () => {
        app.quit();
      }
    }
  ];
}

/**
 * Reflect a recording-state transition in the menubar icon. The
 * tooltip + setTitle text both flip while the recorder is active so
 * the user sees the live state without having to open the popover.
 *   - countdown phase → "● 3 / 2 / 1"
 *   - recording phase → "● REC"
 *   - finalizing      → "● …"
 *   - idle/ready/etc. → restore default tooltip + clear title
 *
 * Stays in lock-step with the right-click menu's Recording row
 * (which reads `isRecordingActive()` at popup time) by reacting to
 * the same `subscribeToRecordingState` stream.
 */
function applyRecordingStateToTray(activeTray: Tray, state: RecordingState): void {
  switch (state.phase) {
    case "countdown":
      activeTray.setTitle(`● ${state.secondsRemaining}`);
      activeTray.setToolTip(`PwrSnap — recording starts in ${state.secondsRemaining}…`);
      return;
    case "preflight":
      activeTray.setTitle("● …");
      activeTray.setToolTip("PwrSnap — preparing to record");
      return;
    case "starting":
      activeTray.setTitle("● ⋯");
      activeTray.setToolTip("PwrSnap — starting recorder");
      return;
    case "recording":
      activeTray.setTitle("● REC");
      activeTray.setToolTip("PwrSnap — recording. Click the tray and choose Stop.");
      return;
    case "stopping":
      activeTray.setTitle("● ⏳");
      activeTray.setToolTip("PwrSnap — finalizing recording");
      return;
    case "processing":
      activeTray.setTitle("● ⏳");
      activeTray.setToolTip("PwrSnap — processing recording");
      return;
    case "idle":
    case "ready":
    case "failed":
      activeTray.setTitle("");
      activeTray.setToolTip(idleTrayTooltip());
      return;
  }
}
