// The tray, on all three platforms. TWO SURFACES, not one — see
// `traySurfaceForPlatform` for why the split is forced rather than chosen:
//
//   • macOS + Windows (`popover`): the icon toggles PwrSnap's own
//     BrowserWindow popover, anchored to `tray.getBounds()`; the native
//     Menu is the right-click fallback.
//   • Linux (`native-menu`): the native Menu, attached with
//     `setContextMenu`, is the ONLY surface. `getBounds()`,
//     `popUpContextMenu()` and the `right-click` event are all
//     `@platform darwin,win32`, and Wayland forbids a client positioning
//     its own windows — so there is nothing to anchor a popover to, no
//     gesture to open it with, and nowhere to put it. Also documented in
//     AGENTS.md "The Linux tray is a native menu" and
//     docs/linux-tray-support.md.
//
// Popover-specific behavior, from the Phase 1.7 deepening review:
//   • Real 16×16/@2x template PNG (generated by scripts/generate-tray-icon.mjs
//     from the brand mark SVG). Template images automatically adapt
//     to dark / light / accent menubars — setTitle() text doesn't.
//   • Popover dismiss-on-blur with a 120ms debounce + DevTools open
//     guard + cursor-bounds check, matching Raycast / Linear / Bartender
//     patterns. Avoids the false-positives the original blur-only
//     handler caused (DevTools focus, dragging the popover, focus
//     hopping to a child popover all looked like "click outside").
//   • screen.getDisplayMatching(trayBounds) for multi-display anchoring.
//   • Right-click opens a real Menu (Quit / Open / Settings) — popover
//     is for the rich UI, the native menu is the fallback.

import { existsSync } from "node:fs";
import { join } from "node:path";
import {
  app,
  ipcMain,
  Menu,
  type MenuItemConstructorOptions,
  nativeImage,
  screen,
  Tray,
  type BrowserWindow
} from "electron";
import {
  DEFAULT_HOTKEYS,
  normalizeAccelerator,
  shortcutPlatformFromString,
  type HotkeyRegistrationStatusSnapshot,
  type HotkeySettingKey,
  type RecordingState,
  type Settings,
  type ShortcutPlatform
} from "@pwrsnap/shared";
import { bus } from "./command-bus";
import { dispatchInteractiveCapture } from "./capture/capture-trigger";
import { getMainLogger } from "./log";
import { logLinuxTrayHostDiagnostics } from "./linux-status-notifier-host";
import { getRuntimeProcessRole } from "./process-role";
import {
  getRecordingState,
  subscribeToRecordingState
} from "./recording/recording-state";
import {
  canStartRecordingAttempt,
  canRunRecordingControl,
  recordingBackendCapabilities
} from "./recording/recording-capabilities";
import {
  canRecordingControllerConfirmDiscard,
  requestRecordingDiscardConfirmation
} from "./recording/recording-controller";
import { createTrayWindow, positionTrayWindow } from "./window";

const log = getMainLogger("pwrsnap:tray");

const BLUR_DISMISS_DEBOUNCE_MS = 120;

/**
 * Hand a destructive recording control off to the HUD's own confirm.
 *
 * ⚠️  This must never become a `dialog.showMessageBox`. A native alert
 * raised from the main process has no content protection and is
 * centred on the display, so it is squarely inside almost any recorded
 * rect: ScreenCaptureKit records it on macOS (only the HUD window is
 * excluded, via `setContentProtection(true)`) and FFmpeg `gdigrab`
 * records it unconditionally on Windows, where the tray offers both
 * items too. The dialog's default button was "Keep Recording", so the
 * path that ruined a take was the one where the user changed their
 * mind: the take survived with several seconds of a PwrSnap alert
 * baked into the MP4.
 *
 * Same class as the two invariants in AGENTS.md — "Tray popover hide"
 * (an NSPanel fade landed in users' screenshots) and "The recording
 * frame may never paint inside the recorded rect".
 *
 * The HUD already owns a two-press arm/confirm for exactly these two
 * actions, and it is the only surface that is content-protected on
 * macOS and anchored outside the rect on Windows. So the tray arms it
 * and gets out of the way; the user confirms where they are already
 * looking at the recording controls.
 */
function confirmDiscardRecording(action: "restart" | "cancel"): void {
  if (requestRecordingDiscardConfirmation(action)) return;
  // The menu only offers these items while the HUD can host the
  // confirm, so this is the narrow race where it died in between.
  // Dispatching anyway would discard the take with no confirmation at
  // all, which is worse than doing nothing: Stop and Save is still in
  // the menu.
  log.warn("no HUD could host the confirm; tray recording control did nothing", {
    action
  });
}

/**
 * Extra menu items appended to the right-click menu (after a
 * separator). Used by the dev seeder to add "Seed perf dataset > …"
 * entries in DEV builds. Empty in production. Not a registration API
 * with deduplication — caller controls the array.
 */
let extraMenuItems: MenuItemConstructorOptions[] = [];

/**
 * Append items to the tray's right-click menu. Returns a `restore`
 * function that drops the items. Call from `registerDevSeeder()`.
 *
 * Both the set and the restore re-publish the Linux menu — there the menu
 * is a persistent D-Bus object built once, not a template read at
 * right-click time, so an unpublished mutation is simply invisible.
 */
export function setExtraTrayMenuItems(items: MenuItemConstructorOptions[]): () => void {
  extraMenuItems = items;
  refreshNativeTrayMenu();
  return () => {
    extraMenuItems = [];
    refreshNativeTrayMenu();
  };
}
const TRAY_RESIZE_CHANNEL = "tray:resize";

/** Hard floor + ceiling so a renderer bug can't shrink to nothing or grow off-screen.
 *  Ceiling raised from 720 → 880 (original redesign) → 1040 (when the
 *  last-snap video export row swapped the 2-button GIF/MP4 strip for
 *  the full 6-card grid (GIF L/M/H + MP4 L/M/H) — same chrome the
 *  library DetailRail renders, so the user can copy / drag any preset
 *  straight from the tray). The 6-card grid adds ~120px over the
 *  prior 2-button row. Image tray stays well under the old 880
 *  ceiling; the bump is purely for video. The popover is anchored
 *  top-down from the menubar tray icon, so growing taller doesn't
 *  push off-screen — Electron clamps to workArea automatically. */
const TRAY_HEIGHT_MIN = 200;
const TRAY_HEIGHT_MAX = 1040;
/** Window width is fixed by the design — must match `.ps-tray { width }`
    in library.css. Bumped from 380 → 440 because the 2-column mode
    grid (Region/Window, Full/All, Timed) was clipping the right column
    at 380, especially with multi-key shortcuts like ⌘⇧F that need 56px
    just for the kbds. */
const TRAY_WIDTH = 440;

let tray: Tray | null = null;
let trayWindow: BrowserWindow | null = null;
/**
 * Last valid renderer measurement accepted by the production resize channel.
 * BrowserWindow.getContentSize() is not a trustworthy applied-size signal on
 * every platform: under some scaled Windows displays it can keep
 * reporting the 440px constructor frame after the renderer viewport and
 * capturePage surface have correctly shrunk to 302px. Keep the renderer's
 * requested DIP height as the resize/readiness contract; E2E additionally
 * reads `innerHeight` to prove the compositor actually received it.
 */
let lastTrayResizeRequest: { cssHeight: number; dipHeight: number } | null = null;
let pendingDismiss: ReturnType<typeof setTimeout> | null = null;
let currentTrayHotkeys: Settings["hotkeys"] = { ...DEFAULT_HOTKEYS };
let resolveTrayHotkeyStatus: (() => HotkeyRegistrationStatusSnapshot) | null = null;

function idleTrayTooltip(): string {
  return "PwrSnap — Quick Capture";
}

export function setTrayHotkeys(
  hotkeys: Settings["hotkeys"],
  resolveStatus: () => HotkeyRegistrationStatusSnapshot
): void {
  currentTrayHotkeys = { ...hotkeys };
  resolveTrayHotkeyStatus = resolveStatus;
  if (tray !== null && canStartRecordingAttempt(getRecordingState())) {
    tray.setToolTip(idleTrayTooltip());
  }
  // The menu labels advertise the accelerators PwrSnap currently owns, so a
  // hotkey change rewrites them. Free on macOS/Windows (rebuilt at
  // right-click); on Linux the published menu has to be replaced.
  refreshNativeTrayMenu();
}

/**
 * A native-menu label is allowed to advertise only a shortcut PwrSnap owns
 * in the OS right now. Persisted spelling is untrusted legacy input: parse it
 * against the explicit host platform, and omit it if runtime ownership is
 * inactive or the spelling is no longer supported there.
 */
function activeTrayAccelerator(
  kind: HotkeySettingKey,
  platform: ShortcutPlatform
): string | null {
  if (resolveTrayHotkeyStatus === null) return null;
  let status: HotkeyRegistrationStatusSnapshot;
  try {
    status = resolveTrayHotkeyStatus();
  } catch (cause) {
    log.warn("failed to read tray hotkey registration status", {
      kind,
      message: cause instanceof Error ? cause.message : String(cause)
    });
    return null;
  }
  const item = status[kind];
  const persisted = currentTrayHotkeys[kind];
  if (item.state !== "active" || item.accelerator !== persisted) return null;
  const normalized = normalizeAccelerator(persisted, platform);
  if (!normalized.ok || normalized.unbound) return null;
  return normalized.normalized;
}

/**
 * Take the popover off screen with NO fade, then restore it on show.
 *
 * The tray popover is a macOS `NSPanel` (`type: 'panel'` — see
 * createTrayWindow in window.ts for why). AppKit resolves a panel's
 * default `NSWindowAnimationBehaviorDefault` to
 * `NSWindowAnimationBehaviorUtilityWindow`, so `[NSWindow orderOut:]`
 * — which is what `BrowserWindow.hide()` calls — plays a ~0.2s
 * FADE-OUT rather than clearing the window on the next frame.
 *
 * That fade ends up inside the user's screenshots. A capture started
 * from a tray button dismisses the popover and then waits a 50ms
 * compositor flush before freezing the screen (see
 * `hidePwrSnapChromeAndSettle` in capture-handlers.ts and the
 * pre-snapshot hide in region-selector.ts). 50ms into a 200ms fade the
 * popover is still ~70% opaque — and the region/auto path CROPS THAT
 * FROZEN SNAPSHOT, so a half-dissolved PwrSnap popover is alpha-blended
 * into the saved capture. The same capture taken with the global hotkey
 * (popover never open) is clean, which is what makes this look like a
 * compositor mystery instead of a window animation.
 *
 * Electron exposes no `animationBehavior` setter, so we take the window
 * to alpha 0 FIRST. `-[NSWindow setAlphaValue:]` applies immediately —
 * there is no implicit animation outside an `NSAnimationContext` — so
 * the fade then runs 0 → 0 and paints nothing. Every show path restores
 * alpha to 1 before ordering the panel back in, or the popover would
 * come back as an invisible window that still eats clicks.
 *
 * Windows is deliberately excluded. There the tray window is
 * `transparent: true`, and `setOpacity` drives whole-window layered
 * alpha (`SetLayeredWindowAttributes`), which is mutually exclusive with
 * the per-pixel alpha (`UpdateLayeredWindow`) a transparent window
 * composites through — the same trap documented on `parkOffScreen` in
 * float-over.ts, where an opacity round-trip left the toast blank.
 * Windows has no NSPanel fade to fix, so there is nothing to trade for.
 *
 * Pinned by tray-instant-hide.test.ts. ALL tray hides go through
 * `hideTrayWindowNow` — not just the capture path. A fade started by
 * some other dismissal (blur, tray-icon toggle, right-click) is just as
 * capturable, and worse: AppKit orders the window out at the START of
 * the fade, so `isVisible()` already reads false and the capture path's
 * own dismiss would skip it and let the fade paint itself in anyway.
 */
function hideTrayWindowNow(window: BrowserWindow): void {
  // Cancel any armed blur-dismiss. Without this, only the capture path
  // (`hideTrayPopoverIfVisible`, which clears it separately) is safe:
  // clicking the tray icon to close arms the timer via the status-item
  // blur, and if the user re-opens within the 120ms debounce before
  // AppKit's NSWindowDidBecomeKeyNotification lands, the stale timer
  // fires, reads `isFocused() === false`, and hides the popover the
  // user just re-opened. The blur callback nulls `pendingDismiss`
  // before calling us, so this is a no-op on that path.
  if (pendingDismiss !== null) {
    clearTimeout(pendingDismiss);
    pendingDismiss = null;
  }
  if (process.platform === "darwin") {
    window.setOpacity(0);
  }
  window.hide();
}

/**
 * Counterpart to {@link hideTrayWindowNow} — undo the alpha-0 park
 * before the panel is ordered back in.
 *
 * ⚠️  EVERY path that puts the popover on screen MUST go through here.
 * `hideTrayWindowNow` leaves the panel at alphaValue 0, so a bare
 * `showInactive()` / `show()` brings it back ordered-in and key but
 * completely invisible — while still hit-testing, so the user's clicks
 * land on a window they cannot see. That failure is worse and much
 * harder to diagnose than the fade this pair exists to kill.
 * `tray-instant-hide.test.ts` grep-asserts this file for stray show
 * calls so a new entry point can't quietly reintroduce it.
 *
 * Known limitation: the panel animation this pair defeats on the hide
 * side also fades the popover IN, and we can't suppress that without
 * hiding what we're trying to show. It only matters for `timed` mode,
 * which snapshots with `keepPwrSnapChrome` (no hide, no compositor
 * flush) — a tray re-opened in the last ~200ms of the countdown is
 * frozen mid-fade-in. Fixing that means holding the snapshot until the
 * fade settles, which trades a rare artifact for latency on every timed
 * capture; not worth it until someone actually hits it.
 */
function showTrayWindowNow(window: BrowserWindow): void {
  if (process.platform === "darwin") {
    window.setOpacity(1);
  }
  window.showInactive();
  window.focus();
}

/**
 * Synchronously hide the tray popover, bypassing the 120ms blur-dismiss
 * debounce. Called from the capture flow right before we shell out to
 * `screencapture` so the popover doesn't show up in the captured frame.
 *
 * The tray popover is a `BrowserWindow` (not an `NSStatusItem` menu),
 * so it does NOT auto-dismiss on click the way a real status-bar menu
 * does — we have to dismiss it ourselves. Belt-and-suspenders against
 * a future change to a real `NSStatusItem`-backed menu (which would
 * dismiss synchronously, and then this becomes a defensible no-op).
 *
 * Idempotent and null-safe — calling on a destroyed or already-hidden
 * window is a no-op. Cancels any pending blur-debounce timeout so we
 * don't get a double-hide jitter when the queued timer fires later.
 */
export function hideTrayPopoverIfVisible(): void {
  if (pendingDismiss !== null) {
    clearTimeout(pendingDismiss);
    pendingDismiss = null;
  }
  if (trayWindow !== null && !trayWindow.isDestroyed() && trayWindow.isVisible()) {
    hideTrayWindowNow(trayWindow);
  }
}

/**
 * What the tray's primary surface IS on this platform.
 *
 * `popover` — macOS and Windows. The tray icon toggles PwrSnap's own
 * `BrowserWindow` popover (createTrayWindow), anchored to
 * `tray.getBounds()`. The native `Menu` is the secondary, right-click
 * affordance.
 *
 * `native-menu` — Linux. The native `Menu` is the ONLY surface, attached
 * with `setContextMenu`. This is not a taste call; four separate pieces of
 * Electron's Linux surface make the popover unbuildable there, and every
 * one of them is stated in electron.d.ts (checked against the pinned
 * electron@41.10.7 — re-check on a major bump):
 *
 *   • `getBounds()` is `@platform darwin,win32`. Measured on Electron
 *     41.10.7 under Linux it returns `{x: 0, y: 0, width: 0, height: 0}` —
 *     so `positionTrayWindow` has no rectangle to consume.
 *   • `popUpContextMenu()` and the `right-click` event are also
 *     `@platform darwin,win32`, so the existing right-click arm cannot
 *     fire and cannot open a menu even if it did. `setContextMenu` is the
 *     only menu API with no platform annotation.
 *   • Under Wayland a client cannot position its own windows at all —
 *     `BrowserWindow.setPosition` is documented "Not supported on Wayland
 *     (Linux)", and `getPosition`/`getBounds` return zeros there because
 *     "introspecting or altering window position is not supported". So
 *     anchoring to the cursor — the obvious X11 fallback — degrades to
 *     "wherever the compositor feels like putting it" on the sessions most
 *     modern distros default to.
 *   • `setContentSize` is documented to "may not work" on Wayland, "as some
 *     window managers restrict programmatic window resizing". That is the
 *     one call the whole resize-to-fit design rests on (AGENTS.md "Tray +
 *     float-over popover sizing"), so even a popover that somehow opened in
 *     the right place could not hug its content.
 *
 * Electron's Linux tray is `StatusIconLinuxDbus`, which speaks the
 * freedesktop StatusNotifierItem protocol over D-Bus directly (it stopped
 * going through libappindicator in Electron 22 — electron/electron#36333).
 * So there is no `libayatana-appindicator3` runtime dependency to declare;
 * what a Linux user needs is an SNI *host* in their desktop. See
 * docs/linux-tray-support.md.
 *
 * Keyed off `ShortcutPlatform`, whose `shortcutPlatformFromString`
 * fallback is `"linux"` — so any platform that is not macOS or Windows
 * gets the native menu, which is the right default for an unknown Unix.
 */
export type TraySurface = "popover" | "native-menu";

export function traySurfaceForPlatform(platform: ShortcutPlatform): TraySurface {
  return platform === "linux" ? "native-menu" : "popover";
}

function trayIconFileName(platform: ShortcutPlatform): string {
  switch (platform) {
    case "darwin":
      // Alpha-only *template* PNG — the system tints it for dark / light /
      // accent menubars. `nativeImage` picks the @2x/@3x sibling per display.
      return "tray-icon-template.png";
    case "win32":
      // No template tinting in the notification area, so the icon carries
      // its own color. Same @2x/@3x sibling set.
      return "tray-icon.png";
    case "linux":
      // A 48px file with NO @Nx siblings, on purpose. StatusIconLinuxDbus
      // serializes the image's scale-1 bitmap into the SNI `IconPixmap`
      // property and lets the panel scale from there, and `@Nx` siblings do
      // not raise that bitmap — measured, `createFromPath(...).toBitmap()`
      // is 1024 bytes (16×16×4) for the `tray-icon.png` set and 9216
      // (48×48×4) for this file. The @2x/@3x siblings are representations of
      // a 16pt image, so they are simply never the one that gets published.
      // See the comment in scripts/generate-tray-icon.mjs.
      return "tray-icon-linux.png";
  }
}

function resolveTrayIconPath(platform: ShortcutPlatform): string {
  const fileName = trayIconFileName(platform);
  // Production: shipped under Contents/Resources/ via electron-builder.yml's
  // `extraResources`. nativeImage auto-loads the @2x/@3x siblings when
  // given the base path, as long as they're in the same directory.
  const productionPath = join(process.resourcesPath, fileName);
  if (existsSync(productionPath)) return productionPath;
  // Dev: served straight out of the workspace `build/` dir.
  return join(app.getAppPath(), "build", fileName);
}

function ensureTrayWindow(): BrowserWindow {
  if (trayWindow !== null && !trayWindow.isDestroyed()) return trayWindow;
  lastTrayResizeRequest = null;
  const window = createTrayWindow();
  trayWindow = window;
  wireBlurDismiss(window);
  // NOTE: there is deliberately no `zoom-changed` hook here. That
  // event is mouse-wheel-only — it does NOT fire for setZoomFactor,
  // the View-menu zoomIn/zoomOut roles, or Chromium HostZoomMap
  // same-origin propagation (verified empirically), so main cannot
  // observe the zoom changes that actually happen in production.
  // Instead the renderer detects effective-zoom changes itself via a
  // devicePixelRatio media-query listener (see TrayMenu.tsx) and
  // re-posts through the resize channel; wireTrayResizeChannel then
  // re-converts CSS px → DIP with the current zoomFactor. See
  // docs/solutions/2026-07-15-popover-zoom-remeasure-dpr.md.
  window.on("closed", () => {
    if (trayWindow === window) {
      trayWindow = null;
      lastTrayResizeRequest = null;
    }
  });
  return window;
}

/**
 * Listen for tray-renderer resize requests and `setContentSize` so the
 * popover hugs its content. Each call also re-positions to keep the
 * top-right corner anchored under the tray icon (otherwise growing
 * down would push the popover off-screen on a tall display).
 *
 * Idempotent — safe to call from both the production `installTray`
 * boot path and the E2E `showTrayPopoverForE2E` test helper without
 * stacking duplicate ipcMain listeners.
 */
let trayResizeChannelWired = false;
function wireTrayResizeChannel(): void {
  if (trayResizeChannelWired) return;
  trayResizeChannelWired = true;
  ipcMain.on(TRAY_RESIZE_CHANNEL, (event, payload: unknown) => {
    if (
      payload === null ||
      typeof payload !== "object" ||
      typeof (payload as { height: unknown }).height !== "number"
    ) {
      return;
    }
    const requestedCss = (payload as { height: number }).height;
    if (!Number.isFinite(requestedCss)) return;
    if (trayWindow === null || trayWindow.isDestroyed()) return;
    // Ignore a late post from a window that was destroyed/replaced between
    // renderer measurement and IPC delivery.
    if (event.sender !== trayWindow.webContents) return;
    // Renderer measures in CSS pixels (post-zoom). `setContentSize`
    // takes DIP (zoom-independent). When the session's zoomFactor is
    // not 1.0 (e.g. user Cmd-+'d in the library — zoom is shared
    // per-origin via Chromium's HostZoomMap), the two units diverge:
    // a 600 CSS px tall popover at 1.32× zoom is 600 × 1.32 ≈ 792
    // DIP. Without this conversion, the BrowserWindow ends up
    // shorter than the rendered content needs and the popover
    // visibly clips.
    const zoom = trayWindow.webContents.zoomFactor;
    const requestedDip = Math.ceil(requestedCss * zoom);
    const clamped = Math.max(TRAY_HEIGHT_MIN, Math.min(TRAY_HEIGHT_MAX, requestedDip));
    if (lastTrayResizeRequest?.dipHeight === clamped) return;
    // Belt-and-braces: every resize call lifts the implicit minimum
    // size first. The createTrayWindow call already does this once on
    // first construction, but if anything later re-asserts a min size
    // (an unrelated Electron API call, a future BrowserWindow.setBounds
    // wrapper, etc.) the resize would silently clamp again. Cheap to
    // re-call — Electron coalesces same-value setMinimumSize calls.
    trayWindow.setMinimumSize(0, 0);
    trayWindow.setContentSize(TRAY_WIDTH, clamped, false);
    lastTrayResizeRequest = { cssHeight: requestedCss, dipHeight: clamped };
    if (tray !== null && trayWindow.isVisible()) {
      positionTrayWindow(trayWindow, tray.getBounds());
    }
  });
}

/**
 * Dismiss-on-blur with two false-positive guards:
 *   - DevTools opened on the tray (developer is debugging)
 *   - Re-focused during the debounce (false-positive blur from a
 *     macOS focus hop)
 *
 * The cursor-inside-bounds check that used to live here was
 * dropping legitimate dismissals — right-clicking the dock icon
 * fires blur but the cursor often grazes the tray window during
 * the debounce, which the old check interpreted as "user is still
 * here." For a transient popover we want to err on dismissing.
 */
function wireBlurDismiss(window: BrowserWindow): void {
  window.on("blur", () => {
    if (pendingDismiss !== null) return;
    pendingDismiss = setTimeout(() => {
      pendingDismiss = null;
      if (trayWindow === null || trayWindow.isDestroyed()) return;
      // DevTools open on the tray = developer using it; never auto-dismiss.
      if (trayWindow.webContents.isDevToolsOpened()) return;
      // If the window regained focus during the debounce window, abort.
      if (trayWindow.isFocused()) return;
      hideTrayWindowNow(trayWindow);
    }, BLUR_DISMISS_DEBOUNCE_MS);
  });
  window.on("focus", () => {
    if (pendingDismiss !== null) {
      clearTimeout(pendingDismiss);
      pendingDismiss = null;
    }
  });
}

export function installTray(): Tray {
  if (tray !== null) return tray;

  const platform = shortcutPlatformFromString(process.platform);
  const surface = traySurfaceForPlatform(platform);

  // The Linux tray has no popover (see `traySurfaceForPlatform`), so it
  // needs neither the resize channel nor the renderer behind it.
  if (surface === "popover") wireTrayResizeChannel();

  const iconPath = resolveTrayIconPath(platform);
  const icon = nativeImage.createFromPath(iconPath);
  if (icon.isEmpty()) {
    log.warn("tray icon image is empty — falling back to setTitle text", { iconPath });
  }
  // Template image is a macOS concept (alpha-only, system-tinted). On
  // Windows/Linux the icon carries its own color — marking it as a template
  // would blank it out.
  if (platform === "darwin") {
    icon.setTemplateImage(true);
  }

  // Linux takes the PATH, not the NativeImage. `StatusIconLinuxDbus`
  // publishes the image as an SNI pixmap either way, so this is belt-and-
  // braces against Electron's long-standing Linux preference for a real
  // file on disk — and it costs nothing, because the `isEmpty()` probe
  // above already gave us the diagnostic a NativeImage was worth.
  tray = new Tray(surface === "native-menu" ? iconPath : icon);
  tray.setToolTip(idleTrayTooltip());

  // Recording state → tray indicator. While recording, prepend "● " to
  // the tooltip + tray title so the menubar telegraphs the live state
  // at a glance (matches OBS / CleanShot conventions). The right-
  // click menu also flips its top items (read in the `right-click`
  // handler below from `isRecordingActive()`).
  subscribeToRecordingState((state) => {
    if (tray === null) return;
    applyRecordingStateToTray(tray, state);
  });

  if (surface === "native-menu") {
    // THE menu, not a right-click extra — and the call that makes the
    // indicator usable at all. `popUpContextMenu` and the `right-click`
    // event are both `@platform darwin,win32`, so without this a Linux
    // user has an icon (at best) that does nothing when clicked. Some SNI
    // hosts additionally refuse to show an item whose `Menu` property they
    // cannot resolve, which is the shape of "no indicator appears at all".
    refreshNativeTrayMenu();
    // Fire-and-forget: names the desktop, the session type, and whether an
    // SNI host is actually listening, so a "no tray icon on Linux" report
    // arrives already diagnosed. Never gates tray creation — an SNI watcher
    // that starts AFTER us is picked up by Chromium's own NameOwnerChanged
    // handling, so a missing host now is not permanent.
    void logLinuxTrayHostDiagnostics();
    log.info("tray installed", { iconPath, surface });
    return tray;
  }

  // Split mode only: double-click opens the Library (a real action), so
  // don't suppress double-clicks. Combined mode keeps the prior behavior
  // (ignore double-clicks) so the experiment-off app is unchanged — the
  // double-click handler below is wired only outside combined.
  const trayDoubleClickOpensLibrary = getRuntimeProcessRole() !== "combined";
  tray.setIgnoreDoubleClickEvents(!trayDoubleClickOpensLibrary);

  tray.on("click", () => toggleTrayWindow());
  if (trayDoubleClickOpensLibrary) {
    tray.on("double-click", () => {
      // The first click of the pair already fired `click` and toggled
      // the popover — drop it so the Library doesn't open underneath an
      // orphaned popover.
      if (trayWindow !== null && !trayWindow.isDestroyed() && trayWindow.isVisible()) {
        hideTrayWindowNow(trayWindow);
      }
      // library:focus spawns (or raises) the Library — same verb as the
      // context menu's "Open Library".
      void bus.dispatch("library:focus", {}, { principal: "ipc" });
    });
  }
  tray.on("right-click", () => {
    const trayBounds = tray?.getBounds();
    // Always dismiss the popover before the context menu appears —
    // having both visible at once is confusing UX (and was the
    // dock-icon-right-click reproduction the user reported).
    if (trayWindow !== null && !trayWindow.isDestroyed() && trayWindow.isVisible()) {
      hideTrayWindowNow(trayWindow);
    }
    const menu = Menu.buildFromTemplate(buildTrayContextMenuTemplate(trayBounds));
    tray?.popUpContextMenu(menu);
  });

  // Pre-warm the popover BrowserWindow at boot. Without this, the
  // first tray click pays the full cost of spawning a Chromium
  // renderer process, loading the renderer bundle, parsing it, and
  // waiting for the initial measurement to settle before the
  // BrowserWindow snaps from its constructor frame (440×440) to the
  // measured content height. With pre-warm, the window is already
  // sized + measured (off-screen, hidden) by the time the user
  // clicks — `toggleTrayWindow` just calls `showInactive()` + `focus()`.
  //
  // Cost: the tray BrowserWindow stays resident from boot. Under
  // Chromium's process-per-site default the tray, library, and
  // region selectors all load the same file:// origin and share one
  // renderer process — so the marginal memory cost is the tray
  // window's display surface, not a separate renderer process. The
  // tray is the most-clicked surface in the menubar UX; this trade
  // pays back on the first click and every click after.
  //
  // We deliberately don't `show()` here — the window stays
  // off-screen + hidden. The renderer's `useLayoutEffect` posts the
  // initial resize over the IPC channel exactly as it does on a real
  // click; `wireTrayResizeChannel` sizes the (hidden) window to match.
  prewarmTrayWindow();

  log.info("tray installed", { iconPath, surface });
  return tray;
}

/**
 * Rebuild the Linux native tray menu and re-attach it.
 *
 * Two reasons this is a function and not a one-shot call in `installTray`:
 *
 *   1. On macOS and Windows the menu is built fresh inside the
 *      `right-click` handler, so it is never stale. On Linux it is a
 *      PERSISTENT D-Bus menu, and Electron's own docs are explicit that
 *      "in order for changes made to individual `MenuItem`s to take
 *      effect, you have to call `setContextMenu` again." Our template is
 *      rebuilt wholesale anyway, so every input that can change a label or
 *      an `enabled` flag has to come back through here: recording phase,
 *      hotkey ownership, and the dev seeder's extra items.
 *   2. It is the one place that knows the refresh is Linux-only, so the
 *      callers stay unconditional.
 *
 * No-op before `installTray` and on the popover platforms.
 *
 * Non-fatal on purpose. Its callers are not places a failure may propagate
 * from: `installTray` runs un-awaited inside `app.whenReady().then(...)`, so
 * a throw there aborts the rest of the boot (focus sink, selector pre-warm);
 * `setTrayHotkeys` runs on every settings write, so a throw would surface as
 * a failed settings patch. The worst honest outcome of a failed publish is a
 * tray that does nothing — the same state this whole change exists to fix,
 * but not a reason to take the app down with it. Logged at error, because
 * `setContextMenu` has no platform annotation and is the documented Linux
 * path, so a failure here means something is wrong that we want to see.
 */
function refreshNativeTrayMenu(): void {
  if (tray === null) return;
  if (traySurfaceForPlatform(shortcutPlatformFromString(process.platform)) !== "native-menu") {
    return;
  }
  try {
    // No `trayBounds`: `getBounds()` is `@platform darwin,win32`, so there is
    // nothing honest to pass. `settings:open` already treats `sourceBounds` as
    // optional and centres the window without it.
    tray.setContextMenu(Menu.buildFromTemplate(buildTrayContextMenuTemplate()));
  } catch (cause) {
    log.error("failed to publish the linux tray menu", {
      message: cause instanceof Error ? cause.message : String(cause)
    });
  }
}

/**
 * Off-screen pre-warm of the tray BrowserWindow. Idempotent — safe
 * to call from `installTray()` AND from the E2E bridge before
 * `measureTrayFirstPaintForE2E`. The window is created in its hidden
 * state via `createTrayWindow`, attached to the resize channel, and
 * left alone: Chromium spawns the renderer, loads the bundle, runs
 * the initial React render + `useLayoutEffect` measurement, and the
 * `tray:resize` IPC sizes the (hidden) window to its content height
 * — all before the user's first click. The first user-visible paint
 * happens at `showInactive()` time on click, but it lands at the
 * already-correct size, so no resize flicker is visible.
 *
 * Returns the window so E2E callers can attach test-only listeners
 * before the renderer mounts; production callers (just `installTray`)
 * discard the return value.
 */
export function prewarmTrayWindow(): BrowserWindow {
  wireTrayResizeChannel();
  return ensureTrayWindow();
}

function toggleTrayWindow(): void {
  const window = ensureTrayWindow();
  if (window.isVisible()) {
    hideTrayWindowNow(window);
    return;
  }
  const bounds = tray!.getBounds();
  positionTrayWindow(window, bounds);
  // Apply vibrancy *after* position so external displays don't render
  // it opaque — known Electron quirk on Sonoma+ multi-monitor setups.
  try {
    window.setVibrancy("popover");
  } catch {
    /* not all macOS versions accept all vibrancy values; non-fatal */
  }
  // Show, then promote to key window. The two-step matters:
  //
  //   1. `showInactive()` paints the panel without activating the
  //      owning app (this is what `type: 'panel'` is for — a
  //      non-activating NSPanel).
  //   2. `focus()` makes the panel the macOS *key window*. On
  //      Electron 28+ with PR #40307 this is non-activating for
  //      panel windows — the panel becomes key, but the app does
  //      NOT come to the foreground.
  //
  // Why bother making it key? Click-outside-to-dismiss. Cocoa fires
  // `NSWindowDidResignKeyNotification` (which Electron surfaces as
  // `blur`) only when the panel was previously key. Without step 2
  // the popover never becomes key, so blur never fires, so the
  // dismiss-on-blur handler in wireBlurDismiss can't see clicks
  // outside the popover. Promoting to key on show reverses that —
  // any click outside the popover (other apps, the desktop, another
  // PwrSnap window) costs the panel its key status and fires blur.
  //
  // The Library-cascade concern from the original implementation
  // (Cocoa picking the next-key window of our app when the panel
  // hides) is handled by the floating-level focus-sink installed
  // at startup — see focus-sink.ts.
  //
  // `showTrayWindowNow` lifts the alpha-0 park a previous
  // `hideTrayWindowNow` left behind before either of those steps.
  showTrayWindowNow(window);
}

export function disposeTray(): void {
  if (pendingDismiss !== null) {
    clearTimeout(pendingDismiss);
    pendingDismiss = null;
  }
  ipcMain.removeAllListeners(TRAY_RESIZE_CHANNEL);
  trayResizeChannelWired = false;
  if (trayWindow !== null && !trayWindow.isDestroyed()) {
    trayWindow.destroy();
    trayWindow = null;
  }
  lastTrayResizeRequest = null;
  if (tray !== null) {
    tray.destroy();
    tray = null;
  }
  currentTrayHotkeys = { ...DEFAULT_HOTKEYS };
  // Reset the RESOLVER too, not just the spellings. The two are read together
  // by `activeTrayAccelerator` — it compares the resolver's live accelerator
  // against `currentTrayHotkeys` — so dropping one and keeping the other
  // leaves a disposed tray's status callback describing hotkey ownership that
  // the next `installTray` has not re-established.
  resolveTrayHotkeyStatus = null;
}

/**
 * E2E-only: ensure the tray popover BrowserWindow exists, the resize
 * channel is wired, and the window is visible. Skips the `Tray` icon
 * creation that `installTray()` does — tests don't need a menubar
 * NSStatusItem, and creating one in headless CI environments is
 * unreliable.
 *
 * Positions the popover at a fixed top-left location on the primary
 * display so spec assertions about bounds are stable across machines.
 */
export function showTrayPopoverForE2E(): void {
  wireTrayResizeChannel();
  const window = ensureTrayWindow();
  // Stable test position: top-left of the primary display, indented
  // a few pixels off the menubar. Production positioning happens via
  // positionTrayWindow + the tray icon's bounds; tests don't have a
  // tray icon, so we just pin the window somewhere predictable.
  const primary = screen.getPrimaryDisplay();
  const wa = primary.workArea;
  window.setPosition(wa.x + 8, wa.y + 8, false);
  showTrayWindowNow(window);
}

/** E2E-only: hide the tray popover synchronously (no debounce). */
export function hideTrayPopoverForE2E(): void {
  hideTrayPopoverIfVisible();
}

/**
 * E2E-only: measurement of "tray click → fully-painted popover" for
 * the perf baseline / regression spec. Two operating modes,
 * determined by the live tray-window state:
 *
 *   - cold: no tray window exists. The bridge creates it, attaches
 *     event listeners, shows it, waits for the renderer's resize to
 *     stabilize. Mirrors today's first-click production flow.
 *   - prewarmed: a tray window already exists, created at boot by
 *     `prewarmTrayWindow()`. The bridge skips construction and just
 *     times `show() → paint`. Mirrors the optimized production flow.
 *
 * Checkpoint set is the same shape across both modes — fields that
 * don't apply in `prewarmed` (windowCreated, domReady, etc.) come
 * back as `null` so spec consumers can print one uniform table.
 */
export async function measureTrayFirstPaintForE2E(options: {
  stableMs?: number;
  /**
   * Per-measurement deadline. The default must comfortably exceed the
   * ~10s scheduler-starvation stretches the VS2026 `windows-latest`
   * runner image exhibits (see docs/solutions/
   * 2026-06-13-windows-vs2026-runner-image-e2e-flakes.md §4): in the
   * 2026-07-16 recurrence, boot + first paint ran at normal speed and
   * the seeded-content reflow — normally ~60ms behind the first
   * measurement — stalled just past the then-10s budget, so a
   * starved-but-working renderer timed out by construction. A genuine
   * regression (the reflow never happens) still times out, just
   * slower.
   */
  timeoutMs?: number;
  /**
   * Minimum content height (DIP) the popover must reach before its size
   * is accepted as "stable". Defaults to 0 (no gate).
   *
   * The "no resize for stableMs" heuristic alone is unsound when the
   * popover's final height depends on an async reflow that lands AFTER a
   * quiet period: a seeded last-snap preview is fetched over IPC and its
   * image decoded via pwrsnap-capture://, so the renderer first measures
   * the empty/text-only height (~248) and only later re-measures to the
   * full seeded height (~634). When that second reflow arrives more than
   * stableMs after the first measurement — routine on the slower VS2026
   * runner image — the bare heuristic breaks at ~248, the empty-tray
   * band. Callers that know they seeded content pass the expected floor
   * so the measurement waits for the real content instead of sampling
   * the transient empty state. A height that never reaches the floor
   * times out (`timedOut: true`) — a genuine regression still fails.
   */
  minStableHeight?: number;
} = {}): Promise<{
  mode: "cold" | "prewarmed";
  windowCreated: number | null;
  domReady: number | null;
  didFinishLoad: number | null;
  readyToShow: number | null;
  isVisible: number | null;
  firstResize: number | null;
  stableResize: number | null;
  resizeApplied: number | null;
  finalContentHeight: number | null;
  requestedContentHeight: number | null;
  mainReportedContentHeight: number | null;
  resizeCount: number;
  timedOut: boolean;
}> {
  const stableMs = options.stableMs ?? 300;
  const timeoutMs = options.timeoutMs ?? 30_000;
  const minStableHeight = options.minStableHeight ?? 0;

  const alreadyExists = trayWindow !== null && !trayWindow.isDestroyed();
  const mode: "cold" | "prewarmed" = alreadyExists ? "prewarmed" : "cold";

  if (alreadyExists && trayWindow!.isVisible()) {
    throw new Error("measureTrayFirstPaintForE2E: tray window already visible; hide first");
  }

  const t0 = performance.now();
  const mark = (): number => Math.round((performance.now() - t0) * 100) / 100;

  // Probe listener for the renderer's resize channel. Observes the
  // production listener (wireTrayResizeChannel) without interfering.
  // In the prewarmed case the renderer has already posted its initial
  // measurement during pre-warm; no new resize is expected unless the
  // content changes between pre-warm and show.
  let firstResize: number | null = null;
  let lastResizeAt = 0;
  let resizeCount = 0;
  const probe = (_event: Electron.IpcMainEvent, payload: unknown): void => {
    if (
      payload === null ||
      typeof payload !== "object" ||
      typeof (payload as { height: unknown }).height !== "number" ||
      !Number.isFinite((payload as { height: number }).height)
    ) {
      return;
    }
    resizeCount += 1;
    if (firstResize === null) firstResize = mark();
    lastResizeAt = performance.now();
  };
  // Belt-and-suspenders: wire the production channel in case the
  // bridge runs before installTray() / prewarmTrayWindow() did
  // (E2E mode skips installTray). Idempotent.
  wireTrayResizeChannel();
  ipcMain.on(TRAY_RESIZE_CHANNEL, probe);

  let windowCreated: number | null = null;
  let domReady: number | null = null;
  let didFinishLoad: number | null = null;
  let readyToShow: number | null = null;

  const window = ensureTrayWindow();
  if (!alreadyExists) {
    windowCreated = mark();
    // `ensureTrayWindow` calls `createTrayWindow` which calls
    // `loadRenderer` synchronously — for a same-tick file:// load,
    // `dom-ready` / `did-finish-load` could fire before we attach
    // listeners on the next microtask. Check the load state first
    // and mark immediately if we already missed the event; otherwise
    // attach the `once` listener as usual.
    if (window.webContents.isLoadingMainFrame()) {
      window.webContents.once("dom-ready", () => {
        domReady = mark();
      });
      window.webContents.once("did-finish-load", () => {
        didFinishLoad = mark();
      });
    } else {
      // Already past load — both events fired during construction.
      // Best-effort: mark them at the same instant so spec consumers
      // see a consistent "first paint landed sub-listener-attach" value.
      domReady = mark();
      didFinishLoad = mark();
    }
    window.once("ready-to-show", () => {
      readyToShow = mark();
    });
  }

  // Mirror showTrayPopoverForE2E's positioning so apples-to-apples
  // with tray-sizing.spec.ts.
  const primary = screen.getPrimaryDisplay();
  const wa = primary.workArea;
  window.setPosition(wa.x + 8, wa.y + 8, false);
  showTrayWindowNow(window);

  let isVisible: number | null = null;
  const deadline = performance.now() + timeoutMs;
  const startedAt = performance.now();
  // In the prewarmed case there's no fresh resize to wait on — the
  // renderer measured during pre-warm and the window is already at
  // its content height. Hold long enough for the OS to swap the off-
  // screen window in and the spec can read back isVisible.
  const minimumPrewarmedHoldMs = 60;
  // The seeded content (if any) must have actually landed before we
  // accept the size as final — see `minStableHeight`. A resize request
  // alone is not readiness: Windows can update getContentSize()
  // synchronously while Chromium's renderer viewport still has the old
  // height for another native event-loop turn. Read renderer innerHeight
  // and require it to acknowledge the CSS-height request. This keeps both
  // possible main-process readback lies (stale 440 and optimistic 688) out
  // of the first-paint contract.
  const resizeRequested = (): boolean =>
    !window.isDestroyed() &&
    lastTrayResizeRequest !== null &&
    lastTrayResizeRequest.dipHeight >= minStableHeight;
  let resizeApplied: number | null = null;
  let finalContentHeight: number | null = null;
  const rendererAppliedResize = async (): Promise<boolean> => {
    if (
      !resizeRequested() ||
      window.isDestroyed() ||
      window.webContents.isDestroyed() ||
      lastTrayResizeRequest === null
    ) {
      return false;
    }
    const request = lastTrayResizeRequest;
    try {
      const rendererHeight = (await window.webContents.executeJavaScript(
        "globalThis.innerHeight",
        true
      )) as unknown;
      if (typeof rendererHeight !== "number" || !Number.isFinite(rendererHeight)) {
        return false;
      }
      finalContentHeight = rendererHeight;
      // innerHeight is expressed in renderer CSS pixels, while Electron's
      // setContentSize and our dipHeight telemetry are in DIP. Compare with
      // the original CSS measurement so this remains correct under zoom.
      if (
        lastTrayResizeRequest === request &&
        Math.abs(rendererHeight - request.cssHeight) <= 1
      ) {
        if (resizeApplied === null) resizeApplied = mark();
        return true;
      }
    } catch {
      // The page may still be navigating. Keep polling until the existing
      // deadline; a permanently unavailable renderer reports timedOut=true.
    }
    return false;
  };
  let timedOut = true;
  while (performance.now() < deadline) {
    if (isVisible === null && !window.isDestroyed() && window.isVisible()) {
      isVisible = mark();
    }
    const applied = await rendererAppliedResize();
    if (mode === "prewarmed") {
      if (
        isVisible !== null &&
        performance.now() - startedAt >= minimumPrewarmedHoldMs &&
        applied
      ) {
        timedOut = false;
        break;
      }
    } else if (
      lastResizeAt > 0 &&
      performance.now() - lastResizeAt >= stableMs &&
      applied
    ) {
      timedOut = false;
      break;
    }
    await new Promise((resolve) => setTimeout(resolve, 10));
  }

  ipcMain.off(TRAY_RESIZE_CHANNEL, probe);

  const stableResize = lastResizeAt > 0 ? Math.round((lastResizeAt - t0) * 100) / 100 : null;
  const mainReportedContentHeight = !window.isDestroyed() ? window.getContentSize()[1] : null;
  const requestedContentHeight = lastTrayResizeRequest?.dipHeight ?? null;
  // Preserve the final renderer truth in timeout diagnostics too. The loop
  // normally populated this while checking the acknowledgement; this last
  // read covers destruction/navigation races where no request was accepted.
  if (!window.isDestroyed() && !window.webContents.isDestroyed()) {
    try {
      const rendererHeight = (await window.webContents.executeJavaScript(
        "globalThis.innerHeight",
        true
      )) as unknown;
      if (typeof rendererHeight === "number" && Number.isFinite(rendererHeight)) {
        finalContentHeight = rendererHeight;
      }
    } catch {
      // A crashed/navigating renderer is reported as null and fails the spec's
      // strict final-height assertion with useful checkpoint context.
    }
  }

  return {
    mode,
    windowCreated,
    domReady,
    didFinishLoad,
    readyToShow,
    isVisible,
    firstResize,
    stableResize,
    resizeApplied,
    finalContentHeight,
    requestedContentHeight,
    mainReportedContentHeight,
    resizeCount,
    timedOut
  };
}

/**
 * Show a single character/number next to the menubar tray icon — used
 * by the Timed (5s) capture flow to render the countdown without
 * popping any window that would steal focus from a menu the user is
 * staging for the shot. `null` clears the title back to icon-only.
 *
 * No-op when the Tray isn't installed (E2E specs that exercise the
 * popover without a real NSStatusItem).
 */
export function setTrayCountdown(text: string | null): void {
  if (tray === null) return;
  setTrayTitleIfSupported(tray, text ?? "");
}

/**
 * `Tray.setTitle` is `@platform darwin` — the label beside the macOS
 * menubar icon.
 *
 * Measured inert rather than fatal off macOS: Windows has called it
 * unconditionally since this code was written and shows nothing, and on
 * Electron 41.10.7 under Linux it returns without throwing. So this guard
 * fixes no crash. What it fixes is the code reading as though the recording
 * dot and the timed countdown were visible on three platforms when they are
 * visible on one — and it names what carries the signal on the other two.
 *
 * Windows telegraphs recording state through the tooltip alone. Linux does
 * the same, plus the menu's own "● Recording — Stop and Save" row, which is
 * why `refreshNativeTrayMenu` runs on every phase change.
 */
function setTrayTitleIfSupported(activeTray: Tray, title: string): void {
  if (process.platform !== "darwin") return;
  activeTray.setTitle(title);
}

/** `mm:ss` since `startedAt`, clamped at zero so a clock skew can't print a
 *  negative duration into a menu label. */
function formatElapsed(startedAt: string): string {
  const elapsedSec = Math.max(
    0,
    Math.floor((Date.now() - new Date(startedAt).getTime()) / 1_000)
  );
  const minutes = Math.floor(elapsedSec / 60).toString().padStart(2, "0");
  const seconds = (elapsedSec % 60).toString().padStart(2, "0");
  return `${minutes}:${seconds}`;
}

export function buildTrayContextMenuTemplate(
  trayBounds?: Electron.Rectangle,
  platform: ShortcutPlatform = shortcutPlatformFromString(process.platform)
): MenuItemConstructorOptions[] {
  // macOS/Windows build this template inside the `right-click` handler, so
  // every read below is fresh. Linux publishes it once via `setContextMenu`
  // and replaces it only when `refreshNativeTrayMenu` runs, so anything that
  // would go stale between republishes has to be left out.
  const menuIsPersistent = traySurfaceForPlatform(platform) === "native-menu";
  const quickCaptureAccelerator = activeTrayAccelerator("quickCapture", platform);
  const videoCaptureAccelerator = activeTrayAccelerator("videoCapture", platform);
  const openLibraryAccelerator = activeTrayAccelerator("openLibrary", platform);
  const recordingState = getRecordingState();
  // Pass the platform through rather than letting this read `process.platform`
  // itself: every other platform-dependent read in this function already comes
  // from the argument, and a function that mixes the two cannot be tested for
  // one platform from a CI host running another — which is the reason
  // `recordingBackendCapabilities` takes the parameter in the first place.
  // Runtime behavior is unchanged; the default argument is `process.platform`.
  const recordingCapabilities = recordingBackendCapabilities(platform);
  const canHostDiscardConfirmation = canRecordingControllerConfirmDiscard();
  // Controls are phase- and backend-aware. In particular, Stop is not shown
  // during the Windows countdown (FFmpeg has not spawned yet), and no action
  // is offered while finalization already owns the backend transition.
  const recordingItems: MenuItemConstructorOptions[] = (() => {
    if (
      recordingState.phase === "recording" &&
      canRunRecordingControl(recordingState, recordingCapabilities, "stop")
    ) {
      // The elapsed clock is only honest on a menu that is rebuilt at the
      // moment it opens. On Linux the menu is a PERSISTENT D-Bus object
      // republished on phase changes, and `phase: "recording"` is set exactly
      // once (recording-service.ts) — there is no per-second tick to hang a
      // rebuild off, and inventing one would replace the menu under a user
      // who has it open. So a persistent menu gets no clock rather than a
      // clock frozen at 00:00. The HUD and the Library both show live time.
      //
      // Not reachable today: `recordingBackendCapabilities("linux")` is
      // `backend: "unsupported"` with every control false, so the `stop`
      // guard above already excludes this whole block on Linux. It is here
      // because the freeze is a property of the PERSISTENT MENU, not of the
      // recorder — whoever lands a Linux recording backend should not have to
      // rediscover it. Pinned by tray-linux-native-menu.test.ts, which mocks
      // a capable Linux backend to reach it.
      const label = menuIsPersistent
        ? "● Recording — Stop and Save"
        : `● Recording ${formatElapsed(recordingState.startedAt)} — Stop and Save`;
      // Top of menu changes while recording — the user almost certainly
      // came here to stop, so make Stop the first item and demote the
      // Capture row. Cancel sits next to Stop so a botched recording
      // can be aborted without persisting a Library row.
      return [
        {
          label,
          click: () => {
            void bus.dispatch("recording:stop", {}, { principal: "ipc" });
          }
        },
        // Both discard the take, so both need a confirmation, and the
        // only legal place to run one mid-take is the HUD (see
        // `confirmDiscardRecording`). The trailing ellipsis is the
        // platform convention for "this asks before it acts" and is
        // load-bearing here: the click arms the HUD rather than
        // discarding anything. If the HUD renderer is gone the items
        // are simply not offered — Stop and Save above always is.
        ...(canHostDiscardConfirmation &&
        canRunRecordingControl(recordingState, recordingCapabilities, "restart")
          ? [
              {
                label: "Restart Recording…",
                click: () => {
                  confirmDiscardRecording("restart");
                }
              } satisfies MenuItemConstructorOptions
            ]
          : []),
        ...(canHostDiscardConfirmation &&
        canRunRecordingControl(recordingState, recordingCapabilities, "cancel")
          ? [
              {
                label: "Cancel Recording…",
                click: () => {
                  confirmDiscardRecording("cancel");
                }
              } satisfies MenuItemConstructorOptions
            ]
          : []),
        { type: "separator" }
      ];
    }
    if (
      (recordingState.phase === "preflight" ||
        recordingState.phase === "countdown" ||
        recordingState.phase === "starting") &&
      canRunRecordingControl(recordingState, recordingCapabilities, "cancel")
    ) {
      return [
        {
          label:
            recordingState.phase === "countdown"
              ? `Cancel recording start (${recordingState.secondsRemaining})`
              : "Cancel recording start",
          click: () => {
            void bus.dispatch("recording:cancel", {}, { principal: "ipc" });
          }
        },
        { type: "separator" }
      ];
    }
    if (recordingState.phase === "stopping" || recordingState.phase === "processing") {
      return [
        {
          label:
            recordingState.phase === "stopping"
              ? "Finalizing recording…"
              : "Processing recording…",
          enabled: false
        },
        { type: "separator" }
      ];
    }
    return [];
  })();
  const baseTemplate: MenuItemConstructorOptions[] = [
    {
      label: "Quick Capture…",
      ...(quickCaptureAccelerator !== null
        ? {
            accelerator: quickCaptureAccelerator,
            // On Windows/Linux Electron otherwise installs a second menu-owned
            // accelerator in addition to PwrSnap's transactional global
            // shortcut. The native menu should display the chord only; macOS
            // retains its native menu accelerator behavior.
            ...(platform !== "darwin" ? { registerAccelerator: false } : {})
          }
        : {}),
      click: () => {
        void dispatchInteractiveCapture("native_tray_menu.quick_capture", "auto");
      }
    },
    {
      // The app's two headline verbs sit together above the rule —
      // snap (Quick Capture) then record (Record Video) — mirroring the
      // tray popover + Library header. No sourceWindowId on a tray
      // dispatch, so the record leaves the Library as a valid target.
      label: "Record Video…",
      // Setup, lead-in, live capture, finalization, and durable failure all
      // belong to the existing attempt. Only idle/ready may open a selector.
      enabled: canStartRecordingAttempt(recordingState),
      ...(videoCaptureAccelerator !== null
        ? {
            accelerator: videoCaptureAccelerator,
            ...(platform !== "darwin" ? { registerAccelerator: false } : {})
          }
        : {}),
      click: () => {
        void bus.dispatch("capture:videoInteractive", {}, { principal: "ipc" });
      }
    },
    { type: "separator" },
    {
      // Same conditional-accelerator treatment as Quick Capture and
      // Record Video above — including `activeTrayAccelerator`, which is
      // what keeps this label honest: it omits the chord unless main
      // currently OWNS that registration, and re-parses the persisted
      // spelling for this platform. Reading `currentTrayHotkeys` raw
      // here would print a chord `globalShortcut.register` refused,
      // which is the same fiction the hard-coded "(⌘⇧L)" tooltip was.
      // `openLibrary` ships unbound, so this usually renders bare.
      label: "Open Library",
      ...(openLibraryAccelerator !== null
        ? {
            accelerator: openLibraryAccelerator,
            ...(platform !== "darwin" ? { registerAccelerator: false } : {})
          }
        : {}),
      click: () => {
        void bus.dispatch("library:focus", {}, { principal: "ipc" });
      }
    },
    {
      label: "Settings…",
      click: () => {
        const options: Parameters<typeof bus.dispatch>[2] = { principal: "ipc" };
        if (trayBounds !== undefined) {
          options.sourceBounds = trayBounds;
        }
        void bus.dispatch("settings:open", {}, options);
      }
    }
  ];
  const extras = extraMenuItems.length > 0
    ? [{ type: "separator" } as MenuItemConstructorOptions, ...extraMenuItems]
    : [];
  return [
    ...recordingItems,
    ...baseTemplate,
    ...extras,
    { type: "separator" },
    {
      label: "Quit PwrSnap",
      click: () => {
        app.quit();
      }
    }
  ];
}

/**
 * Reflect a recording-state transition in the menubar icon. The
 * tooltip + setTitle text both flip while the recorder is active so
 * the user sees the live state without having to open the popover.
 *   - countdown phase → "● 3 / 2 / 1"
 *   - recording phase → "● REC"
 *   - finalizing      → "● …"
 *   - idle/ready/etc. → restore default tooltip + clear title
 *
 * Stays in lock-step with the right-click menu's Recording row
 * (which reads `isRecordingActive()` at popup time) by reacting to
 * the same `subscribeToRecordingState` stream.
 */
function applyRecordingStateToTray(activeTray: Tray, state: RecordingState): void {
  // A phase change rewrites the menu's top rows (Stop / Restart / Cancel,
  // and the disabled "Finalizing…" placeholder). macOS and Windows read the
  // template at right-click time and need nothing here; Linux has to
  // re-publish. Do it first so the menu is already correct if the user gets
  // to it before the tooltip write lands.
  refreshNativeTrayMenu();
  switch (state.phase) {
    case "countdown":
      setTrayTitleIfSupported(activeTray, `● ${state.secondsRemaining}`);
      activeTray.setToolTip(`PwrSnap — recording starts in ${state.secondsRemaining}…`);
      return;
    case "preflight":
      setTrayTitleIfSupported(activeTray, "● …");
      activeTray.setToolTip("PwrSnap — preparing to record");
      return;
    case "starting":
      setTrayTitleIfSupported(activeTray, "● ⋯");
      activeTray.setToolTip("PwrSnap — starting recorder");
      return;
    case "recording":
      setTrayTitleIfSupported(activeTray, "● REC");
      activeTray.setToolTip("PwrSnap — recording. Click the tray and choose Stop.");
      return;
    case "stopping":
      setTrayTitleIfSupported(activeTray, "● ⏳");
      activeTray.setToolTip("PwrSnap — finalizing recording");
      return;
    case "processing":
      setTrayTitleIfSupported(activeTray, "● ⏳");
      activeTray.setToolTip("PwrSnap — processing recording");
      return;
    case "idle":
    case "ready":
    case "failed":
      setTrayTitleIfSupported(activeTray, "");
      activeTray.setToolTip(idleTrayTooltip());
      return;
  }
}
