// macOS menubar tray + anchored popover. Phase 1.7 refinements per
// the deepening review:
//   • Real 16×16/@2x template PNG (generated by scripts/generate-tray-icon.mjs
//     from the brand mark SVG). Template images automatically adapt
//     to dark / light / accent menubars — setTitle() text doesn't.
//   • Popover dismiss-on-blur with a 120ms debounce + DevTools open
//     guard + cursor-bounds check, matching Raycast / Linear / Bartender
//     patterns. Avoids the false-positives the original blur-only
//     handler caused (DevTools focus, dragging the popover, focus
//     hopping to a child popover all looked like "click outside").
//   • screen.getDisplayMatching(trayBounds) for multi-display anchoring.
//   • Right-click opens a real Menu (Quit / Open / Settings) — popover
//     is for the rich UI, the native menu is the fallback.

import { join } from "node:path";
import { app, ipcMain, Menu, nativeImage, screen, Tray, type BrowserWindow } from "electron";
import { bus } from "./command-bus";
import { getMainLogger } from "./log";
import { createTrayWindow, positionTrayWindow } from "./window";

const log = getMainLogger("pwrsnap:tray");

const BLUR_DISMISS_DEBOUNCE_MS = 120;
const TRAY_RESIZE_CHANNEL = "tray:resize";

/** Hard floor + ceiling so a renderer bug can't shrink to nothing or grow off-screen. */
const TRAY_HEIGHT_MIN = 200;
const TRAY_HEIGHT_MAX = 720;
/** Window width is fixed by the design (see TrayMenu.css `.ps-tray { width: 100% }`
    inside a 380px window). We don't accept renderer-driven width changes. */
const TRAY_WIDTH = 380;

let tray: Tray | null = null;
let trayWindow: BrowserWindow | null = null;
let pendingDismiss: ReturnType<typeof setTimeout> | null = null;

function resolveTrayIconPath(): string {
  // The tray PNG ships under apps/desktop/build/. In dev,
  // app.getAppPath() resolves to apps/desktop. In production
  // packaged builds, the file lives next to the bundled
  // resources — electron-builder includes `build/` via the
  // `extraResources` mechanism (TODO Phase 3 — for Phase 1, dev
  // path is sufficient).
  return join(app.getAppPath(), "build/tray-icon-template.png");
}

function ensureTrayWindow(): BrowserWindow {
  if (trayWindow !== null && !trayWindow.isDestroyed()) return trayWindow;
  const window = createTrayWindow();
  trayWindow = window;
  wireBlurDismiss(window);
  window.on("closed", () => {
    if (trayWindow === window) trayWindow = null;
  });
  return window;
}

/**
 * Listen for tray-renderer resize requests and `setContentSize` so the
 * popover hugs its content. Each call also re-positions to keep the
 * top-right corner anchored under the tray icon (otherwise growing
 * down would push the popover off-screen on a tall display).
 */
function wireTrayResizeChannel(): void {
  ipcMain.on(TRAY_RESIZE_CHANNEL, (_event, payload: unknown) => {
    if (
      payload === null ||
      typeof payload !== "object" ||
      typeof (payload as { height: unknown }).height !== "number"
    ) {
      return;
    }
    const height = Math.round((payload as { height: number }).height);
    if (!Number.isFinite(height)) return;
    const clamped = Math.max(TRAY_HEIGHT_MIN, Math.min(TRAY_HEIGHT_MAX, height));
    if (trayWindow === null || trayWindow.isDestroyed()) return;
    const current = trayWindow.getContentSize();
    if (current[1] === clamped) return;
    trayWindow.setContentSize(TRAY_WIDTH, clamped, false);
    if (tray !== null && trayWindow.isVisible()) {
      positionTrayWindow(trayWindow, tray.getBounds());
    }
  });
}

/**
 * Dismiss-on-blur with two false-positive guards:
 *   - DevTools opened on the tray (developer is debugging)
 *   - Re-focused during the debounce (false-positive blur from a
 *     macOS focus hop)
 *
 * The cursor-inside-bounds check that used to live here was
 * dropping legitimate dismissals — right-clicking the dock icon
 * fires blur but the cursor often grazes the tray window during
 * the debounce, which the old check interpreted as "user is still
 * here." For a transient popover we want to err on dismissing.
 */
function wireBlurDismiss(window: BrowserWindow): void {
  window.on("blur", () => {
    if (pendingDismiss !== null) return;
    pendingDismiss = setTimeout(() => {
      pendingDismiss = null;
      if (trayWindow === null || trayWindow.isDestroyed()) return;
      // DevTools open on the tray = developer using it; never auto-dismiss.
      if (trayWindow.webContents.isDevToolsOpened()) return;
      // If the window regained focus during the debounce window, abort.
      if (trayWindow.isFocused()) return;
      trayWindow.hide();
    }, BLUR_DISMISS_DEBOUNCE_MS);
  });
  window.on("focus", () => {
    if (pendingDismiss !== null) {
      clearTimeout(pendingDismiss);
      pendingDismiss = null;
    }
  });
}

export function installTray(): Tray {
  if (tray !== null) return tray;

  wireTrayResizeChannel();

  const iconPath = resolveTrayIconPath();
  const icon = nativeImage.createFromPath(iconPath);
  if (icon.isEmpty()) {
    log.warn("tray icon image is empty — falling back to setTitle text", { iconPath });
  }
  icon.setTemplateImage(true);

  tray = new Tray(icon);
  tray.setToolTip("PwrSnap — ⌘⇧P to capture");
  tray.setIgnoreDoubleClickEvents(true);

  tray.on("click", () => toggleTrayWindow());
  tray.on("right-click", () => {
    // Always dismiss the popover before the context menu appears —
    // having both visible at once is confusing UX (and was the
    // dock-icon-right-click reproduction the user reported).
    if (trayWindow !== null && !trayWindow.isDestroyed() && trayWindow.isVisible()) {
      trayWindow.hide();
    }
    const menu = Menu.buildFromTemplate([
      {
        label: "Capture region…",
        accelerator: "CommandOrControl+Shift+P",
        click: () => {
          void bus.dispatch("capture:interactive", {}, { principal: "ipc" });
        }
      },
      { type: "separator" },
      {
        label: "Open Library",
        click: () => {
          void bus.dispatch("library:focus", {}, { principal: "ipc" });
        }
      },
      // Settings still pending — landed in Phase 3. Keep it
      // disabled so the surface signals "coming soon" instead of
      // looking broken.
      { label: "Settings…", enabled: false },
      { type: "separator" },
      { role: "quit" }
    ]);
    tray?.popUpContextMenu(menu);
  });

  log.info("tray installed", { iconPath });
  return tray;
}

function toggleTrayWindow(): void {
  const window = ensureTrayWindow();
  if (window.isVisible()) {
    window.hide();
    return;
  }
  const bounds = tray!.getBounds();
  positionTrayWindow(window, bounds);
  // Apply vibrancy *after* position so external displays don't render
  // it opaque — known Electron quirk on Sonoma+ multi-monitor setups.
  try {
    window.setVibrancy("popover");
  } catch {
    /* not all macOS versions accept all vibrancy values; non-fatal */
  }
  window.show();
  window.focus();
}

export function disposeTray(): void {
  if (pendingDismiss !== null) {
    clearTimeout(pendingDismiss);
    pendingDismiss = null;
  }
  ipcMain.removeAllListeners(TRAY_RESIZE_CHANNEL);
  if (trayWindow !== null && !trayWindow.isDestroyed()) {
    trayWindow.destroy();
    trayWindow = null;
  }
  if (tray !== null) {
    tray.destroy();
    tray = null;
  }
}
